### ISSUE TITLE
Issue with installing dependencies from yml file on M1 mac

### ISSUE THREAD

**Issue by AnaCaldaruse** [bayer-science-for-a-better-life/Img2Mol#12]
After following the install directions I could not install the environment.yml file. I got an error about the cudatoolkit=11.0
I tried to remove that line within yml file, proceed with install instructions, activate env and then install cudatoolkit with the following command <conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch -c conda-forge> but still could not get it to work. Just a note: I am on a M1 mac and I am not sure if that's part of the problem. Has anyone else had this problem or have any advice?
<img width="350" alt="Screen Shot 2023-02-03 at 12 20 54 PM" src="https://user-images.githubusercontent.com/67443041/216705122-740d52f6-3fd1-4519-bfd4-1c4c61b27f0b.png">

**Comment by WilsonWeiWU** [comment]
> After following the install directions I could not install the environment.yml file. I got an error about the cudatoolkit=11.0
> I tried to remove that line within yml file, proceed with install instructions, activate env and then install cudatoolkit with the following command <conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch -c conda-forge> but still could not get it to work. Just a note: I am on a M1 mac and I am not sure if that's part of the problem. Has anyone else had this problem or have any advice?
> <img alt="Screen Shot 2023-02-03 at 12 20 54 PM" width="350" src="https://user-images.githubusercontent.com/67443041/216705122-740d52f6-3fd1-4519-bfd4-1c4c61b27f0b.png">

Hi, I ran into the exact same problem. I read that `cudatoolkit` is no longer supported for Mac past version 9.0. I edited the `environment.yml` file to replace `cudatoolkit=11.0` with `cudatoolkit=9.0` and it worked for me!

Source: https://github.com/CompVis/stable-diffusion/issues/309#issuecomment-1411418748
