### ISSUE TITLE
Kernel restart when running first cell of `example_inference_local_cddd.ipynb`

### ISSUE THREAD

**Issue by WilsonWeiWU** [bayer-science-for-a-better-life/Img2Mol#15]
Hi, I have created a local CDDD conda environment and am trying to run `example_inference_local_cddd.ipynb`, however my Jupyter Notebook kernel keeps on restarting when I try to run the first cell within the notebook. In particular, this line of code

`from img2mol.inference import *`

Unfortunately there's no error code, just this screenshot of the error I get from Jupyter Notebook itself. The same issue repeats after pressing the OK button and running the first cell again.

I believe the CDDD server is also down, as I am getting a connection error that has been reported in Issues before.

![kernal_restart](https://github.com/bayer-science-for-a-better-life/Img2Mol/assets/49481763/232a324a-cb37-4c2d-86f8-b164a3709253)

**Comment by djork** [comment]
There should be error messages displayed in the console prompt where you started the Jupyter Notebook. I close this issue, until you have checked this first.

**Comment by djork** [comment]
See comment above.
