### ISSUE TITLE
Benchmark dataset filtering rules

### ISSUE THREAD

**Issue by OBrink** [bayer-science-for-a-better-life/Img2Mol#5]
Thank you for uploading the exact benchmark datasets that you used to validate Img2Mol! 
I have a question regarding the size of the different sets. It appears that you have removed some images from the original benchmark sets. For example, the JPO dataset normally consists of 450 images but here it is 365. Could you share the criteria for the removal of images from the sets? 
Thanks in advance! :)

**Comment by djork** [comment]
We actually only removed images that either contained Markush structures or rare elements such as Si or Sn.
