### ISSUE TITLE
Reference files for benchmark datasets

### ISSUE THREAD

**Issue by OBrink** [bayer-science-for-a-better-life/Img2Mol#6]
Thank you for uploading the benchmark images. Could you also provide the SD files or a list of SMILES or some sort of reference file that contains the underlying chemical structure? The reference files for the USPTO, UoB, CLEF and JPO sets are available elsewhere but I cannot find references for the STAKER and Img2Mol sets.

Additionally, it is stated that only half of the images from the two bigger sets were used. Could you specify which images were used?

Thanks in advance!

**Comment by djork** [comment]
Hi OBrink, 
I added the mapping info for the STAKER and Img2Mol datasets.
Will close the issue now.
