### ISSUE TITLE
example_inference.ipynb not working

### ISSUE THREAD

**Issue by sujinK12** [bayer-science-for-a-better-life/Img2Mol#8]
Hi 
I get some problem about your code especially cddd_server.py

when i run example_inference.ipynb, it cause ConnectionError like this
ConnectionError: HTTPConnectionPool(host='ec2-18-157-240-87.eu-central-1.compute.amazonaws.com', port=8892): Max retries exceeded with url: /cddd_to_smiles/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff999ca6668>: Failed to establish a new connection: [Errno 110] Connection timed out',))

I'm waiting for your help.

Thanks :)

**Comment by djork** [comment]
This error occurs when the CDDD server crashes (ec2-18-157-240-87.eu-central-1.compute.amazonaws.com). We recommend moving to hosting your own deployment of the CDDD server and the img2mol server if you want to query larger datasets.
This deployment is a demo server and not necessarily hardened for production.
